

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: core-services
  labels:
    app: frontend-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1       
      maxUnavailable: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
      - name: frontend-service
        image: dubemezeagwu/frontend-service:v0.0.1
        ports:
        - containerPort: 5173
        readinessProbe:
          httpGet:
            path: /health
            port: 5173
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5173
          initialDelaySeconds: 10
          periodSeconds: 20
        env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: core-services
spec:
  selector:
    app: frontend-service
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5173
  type: LoadBalancer
